### ISSUE TITLE
Ramses_cc not working after upgrading to HA 2025.5.1

### ISSUE THREAD

**Issue by rverheijdengit** [zxdavb/ramses_cc#250]
I have Ramses_cc working on 225.5.0 with version 0.50.1
I  have an Orcon MVS-15RH CO2B
My config is : 
orphans_hvac:
  - "32:095659"
  - "18:197208"
  - "29:231810"
  - "29:162275"

"18:197208":
  class: HGI
"29:162275":
  _note: Orcon 15RF
  class: REM
  commands:
    auto: " I --- 29:162275 29:231810 --:------ 22F1 003 000404"
    away: " I --- 29:162275 29:231810 --:------ 22F1 003 000004"
    high: " I --- 29:162275 29:231810 --:------ 22F1 003 000304"
    high_15: " I --- 29:162275 29:231810 --:------ 22F3 007 00120F03040404"
    high_30: " I --- 29:162275 29:231810 --:------ 22F3 007 00121E03040404"
    high_60: " I --- 29:162275 29:231810 --:------ 22F3 007 00123C03040404"
    low: " I --- 29:162275 29:231810 --:------ 22F1 003 000104"
    med_60: " I --- 29:162275 29:231810 --:------ 22F3 007 00123C02040404"
    medium: " I --- 29:162275 29:231810 --:------ 22F1 003 000204"
  faked: true
"32:095659":
  class: CO2

When i upgrade to HA 2025.5.1 the integration starts but the FAN doesn't respond anymore when i send the commands.
I tried pairing a new fake remote whoch i added to the above config with : 
service: ramses_cc.bind_device
data:
  device_id: "29:162285"
  offer:
    22F1: null
    22F3: null
    "10E0": null
  device_info: " I --- 29:162285 63:262142 --:------ 10E0 038 000001C894030167FFFFFFFFFFFF1B0807E4564D492D313557534A3533000000000000000000"

When linking my automations to that remote still no response.
I then downgraded HA back to 2025.5.0 and all was working again.

**Comment by seangordon** [comment]
I'm seeing a similar problem with HA 2025.5.1
Also on Ramses_cc  0.50.1

Upgrading to HA 2025.5.1 caused this error to repeatedly appear in the log, and the ramses component constantly failed to initialize:

- 2025-05-08 10:54:39.703 WARNING (MainThread) [custom_components.ramses_cc] Failed to set up entry 01JF0ZCCMRQ11VX2PJ9RQ85820 (will retry): There is a problem with the serial port: Transport did not bind to Protocol within 9 secs (check config)

Downgrading to HA 2025.5.0 fixed the problem

**Comment by seangordon** [comment]
The problem I was seeing has been resolved with the latest update to HA.
Upgraded to HA 2025.5.2 this morning and the Ramses_CC component is working correctly.

**Comment by Asarew** [comment]
unfortunantly this issue still persists for me:
```
2025-05-20 16:00:26.130 WARNING (MainThread) [custom_components.ramses_cc] Failed to set up entry 01JMJDCC7RT1FNGKQR8H087PYQ (will retry): There is a problem with the serial port: Transport did not bind to Protocol within 9 secs (check config)
```

running: 
HA 2025.5.2
ramses_cc: 0.50.1
